# Generated by Django 6.1.1 on 2026-09-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cadastro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_aluno", models.CharField(max_length=200)),
                ("data_nascimento", models.DateField()),
                ("nacionalidade_aluno", models.CharField(max_length=30)),
                ("nome_mae", models.CharField(blank=True, max_length=200)),
                ("numero_mae", models.CharField(blank=True, max_length=20)),
                ("nome_pai", models.CharField(blank=True, max_length=200)),
                ("numero_pai", models.CharField(blank=True, max_length=20)),
                ("endereco", models.CharField(max_length=200)),
                ("bairro", models.CharField(max_length=100)),
                ("numero_casa", models.CharField(max_length=20)),
                (
                    "telefone_extra",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("turma", models.CharField(max_length=50)),
                ("matricula", models.PositiveIntegerField(unique=True)),
            ],
        ),
    ]
