# Generated by Django 6.1.1 on 2026-10-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aluno", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadastro",
            name="endereco",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="cadastro",
            name="nome_aluno",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="cadastro",
            name="nome_mae",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="cadastro",
            name="nome_pai",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
