# Generated by Django 6.1.1 on 2026-10-04 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aluno", "0002_alter_cadastro_endereco_alter_cadastro_nome_aluno_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cadastro",
            name="matricula",
        ),
    ]
