# Generated by Django 6.1.1 on 2026-10-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aluno", "0003_remove_cadastro_matricula"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadastro",
            name="telefone_extra",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
