# Generated by Django 6.1.1 on 2026-10-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aluno", "0004_alter_cadastro_telefone_extra"),
    ]

    operations = [
        migrations.AddField(
            model_name="cadastro",
            name="matricula",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
